'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { CheckCircle2, AlertTriangle, ChevronDown, Download, RotateCcw, Loader2, UserRound, MessageSquareText, Sparkles } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { InterviewArt } from './interview-art';
import type { InterviewReport, InterviewSession, DimensionScore, HistoryStats } from '@/types/interview';
import s from './interview.module.css';
import { ScrollStage } from '@/components/layout/scroll-stage';

export function InterviewReportView({ report, session }: { report: InterviewReport; session: InterviewSession }) {
  const [history,setHistory] = useState<HistoryStats['sessions']>([]);
  const [historyFailed,setHistoryFailed] = useState(false);
  useEffect(()=>{fetch('/api/interview/history/stats',{headers:{}}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(data=>setHistory(Array.isArray(data.sessions)?data.sessions:[])).catch(()=>setHistoryFailed(true));},[]);
  const [filter,setFilter] = useState('all');
  const [expanded,setExpanded] = useState<string|null>(null);
  const [downloading,setDownloading] = useState(false);
  const rounds=useMemo(()=>Array.isArray(report.roundEvaluations)?report.roundEvaluations:[],[report.roundEvaluations]);
  const improvements=Array.isArray(report.improvementPlan)?report.improvementPlan:[];
  const questions=useMemo(()=>rounds.flatMap((round,ri)=>(round.questions||[]).map((q,i)=>({...q,person:round.interviewerName,type:round.interviewerType,id:`${ri}-${i}`}))),[rounds]);
  const visible=questions.filter(q=>filter==='all'||q.type===filter);
  const positives=[...new Set(questions.flatMap(q=>q.highlights||[]))].slice(0,2);
  const warning=improvements[0]?.area||questions.flatMap(q=>q.weaknesses||[])[0];
  const score=Math.max(0,Math.min(100,report.overallScore));
  async function download() {
    if(downloading)return;setDownloading(true);
    try {const r=await fetch(`/api/interview/${session.id}/report/export`,{headers:{}});if(!r.ok)throw new Error();const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`面试报告-${session.jobTitle}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{toast.error('报告下载失败，请稍后重试');}finally{setDownloading(false);}
  }
  const previous=history.filter(item=>item.id!==session.id&&item.jobTitle.trim()===session.jobTitle.trim()&&+new Date(item.createdAt)<+new Date(session.createdAt)).sort((a,b)=>+new Date(b.createdAt)-+new Date(a.createdAt))[0];
  const downloadButton=<Button disabled={downloading} onClick={()=>void download()}>{downloading?<Loader2 size={16} className="animate-spin"/>:<Download size={16}/>}下载报告</Button>;
  return <ScrollStage title={`${session.jobTitle} · 面试报告`} actions={<><Button asChild variant="ghost" size="sm"><Link href="/interview">返回</Link></Button>{downloadButton}</>} sections={[{id:'interview-overview',label:'综合表现'},{id:'interview-evaluators',label:'面试官评价'},{id:'interview-questions',label:'逐题复盘'},{id:'interview-improvements',label:'提升建议'},{id:'interview-comparison',label:'历史对比'}]}><div className={s.reportPage}>
    <header className={s.reportHeader} data-scroll-hero><div className={s.headerArt}><InterviewArt/></div><div><Link href="/interview">模拟面试 · INTERVIEW</Link><h1>面试报告</h1><p>{session.jobTitle} · {session.selectedInterviewers.length} 位面试官 · {new Date(session.createdAt).toLocaleDateString('zh-CN')}</p></div><div><Link href="/interview/new"><Button variant="outline"><RotateCcw size={16}/>再练一次</Button></Link>{downloadButton}</div></header>
    <div className={s.reportTop} id="interview-overview" data-scroll-section><section className={s.reportCard}><h2>综合表现</h2><p className={s.hint}>基于本次面试的整体表现评分</p><div className={s.scoreOverview}><div className={s.scoreGauge}><svg viewBox="0 0 240 195" role="img" aria-label={`综合表现 ${score} 分`}><defs><linearGradient id="interview-gauge"><stop stopColor="#50d2a0"/><stop offset="1" stopColor="#c9f5e6"/></linearGradient></defs><path d="M32 158 A94 94 0 1 1 208 158" pathLength="100" fill="none" stroke="#edf9f4" strokeWidth="17" strokeLinecap="round"/><path className={s.gaugeProgress} d="M32 158 A94 94 0 1 1 208 158" pathLength="100" fill="none" stroke="url(#interview-gauge)" strokeWidth="17" strokeLinecap="round" strokeDasharray={`${score} 100`}/><text x="118" y="120" textAnchor="middle" fontSize="59" fontWeight="650" fill="currentColor">{score}</text><text x="173" y="120" fontSize="14" fill="currentColor">分</text><text x="120" y="155" textAnchor="middle" fontSize="14" fill="#5e6c81">{score>=85?'表现优秀':score>=70?'表现良好':score>=60?'继续进步':'有待提升'}</text></svg></div><div className={s.scoreHighlights}>{positives.map(v=><p key={v}><CheckCircle2 size={16}/><span title={v}>{v}</span></p>)}{warning&&<p data-warning="true"><AlertTriangle size={16}/><span title={warning}>{warning}</span></p>}</div></div>{report.overallFeedback&&<div className={s.overallFeedback}><h3>完整评价</h3><p>{report.overallFeedback}</p></div>}</section>
      <section className={s.reportCard}><h2>能力分布</h2><p className={s.hint}>基于面试内容的能力评估</p><div className={s.abilityGrid}><AbilityRadar dimensions={report.dimensionScores||[]}/><div className={s.abilityLegend}><h3>各项能力得分</h3>{(report.dimensionScores||[]).map(d=><p key={d.dimension}><i/><span>{d.dimension}</span><b>{d.score}</b></p>)}</div></div></section>
    </div>
    <section className={s.reviewCard} id="interview-evaluators" data-scroll-section><h2>面试官综合评价</h2><p className={s.hint}>保留每位面试官的评分、判断依据与反馈</p><div className={s.evaluatorGrid}>{rounds.map((round,index)=><article key={`${round.roundId}-${index}`}><header><strong>{round.interviewerName}</strong><b>{round.score}<small> / 100</small></b></header><p>{round.feedback}</p><span>{round.questions?.length||0} 道问题 · {(round.questions||[]).filter(q=>q.marked).length} 道已收藏</span></article>)}</div></section>
    <section className={s.reviewCard} id="interview-questions" data-scroll-section><h2>逐题复盘</h2><p className={s.hint}>回顾你的回答，查看面试官反馈与改进建议</p><div className={s.reviewTabs}><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>全部（{questions.length}）</button>{rounds.filter((r,i)=>rounds.findIndex(v=>v.interviewerType===r.interviewerType)===i).map(r=><button key={r.interviewerType} aria-pressed={filter===r.interviewerType} onClick={()=>setFilter(r.interviewerType)}>{r.interviewerName}（{questions.filter(q=>q.type===r.interviewerType).length}）</button>)}</div>
      {!visible.length&&<p className={s.hint}>本次没有可供逐题复盘的回答。</p>}
      {visible.map((q,i)=>{const open=expanded===q.id||(expanded===null&&i===0);return <article className={s.questionReview} key={q.id}><button aria-expanded={open} onClick={()=>setExpanded(open?'none':q.id)}><b>Q{questions.findIndex(v=>v.id===q.id)+1}</b><strong>{q.question}</strong><span>{q.person} · {q.score}分{q.marked?' · 已收藏':''}{q.hinted?' · 使用提示':''}{q.skipped?' · 已跳过':''}</span><ChevronDown size={17} style={{transform:open?'rotate(180deg)':undefined}}/></button>{open&&<div className={s.questionAnswer}><p><small>你的回答</small><span>{q.answerSummary||'未作答'}</span></p>{q.highlights?.length>0&&<p data-kind="positive"><small><CheckCircle2 size={14}/>面试官反馈</small><span>{q.highlights.join('；')}</span></p>}<p data-kind="suggestion"><small><AlertTriangle size={14}/>改进建议</small><span>{(q.weaknesses||[]).join('；')||'暂无额外不足记录。'}</span></p>{q.referenceTips&&<p data-kind="reference"><small>参考思路</small><span>{q.referenceTips}</span></p>}</div>}</article>;})}
    </section>
    <section className={s.improvementCard} id="interview-improvements" data-scroll-section><header><div><h2>下一步提升</h2><p className={s.hint}>根据本次面试表现，为你提供个性化的改进建议</p></div>{downloadButton}</header><div>{improvements.map((item,i)=>{const Icon=[UserRound,MessageSquareText,Sparkles][i%3];return <article key={`${item.area}-${i}`}><i data-tone={i%3}><Icon size={23}/></i><div><h3>{item.area} <small className={s.priority} data-priority={item.priority}>{{high:'优先提升',medium:'持续练习',low:'逐步完善'}[item.priority]||item.priority}</small></h3><p>{item.description}</p>{item.resources?.length>0&&<small>{item.resources.join(' · ')}</small>}</div></article>;})}</div></section>
    <section className={s.reviewCard} id="interview-comparison" data-scroll-section><h2>与上次同岗位面试对比</h2>{previous?<><p className={s.hint}>对比 {new Date(previous.createdAt).toLocaleDateString('zh-CN')} 的 {previous.jobTitle} 面试；仅比较名称一致的维度。</p><div className={s.comparisonRows}>{[{dimension:'综合评分',score:report.overallScore,maxScore:100},...(report.dimensionScores||[])].map(d=>{const old=d.dimension==='综合评分'?previous.overallScore:previous.dimensionScores?.find(v=>v.dimension===d.dimension)?.score;const change=old===undefined?undefined:d.score-old;return <div key={d.dimension}><strong>{d.dimension}</strong><span>上次 {old??'未评估'}</span><b>本次 {d.score}</b><em data-positive={change!==undefined&&change>=0}>{change===undefined?'新增评估':`${change>0?'+':''}${change}`}</em></div>;})}</div></>:<p className={s.hint}>{historyFailed?'历史记录暂时无法加载，当前报告已完整显示。':'还没有可比较的同岗位历史报告。完成下一次练习后可查看维度变化。'}</p>}</section>
  </div></ScrollStage>;
}
function AbilityRadar({dimensions}:{dimensions:DimensionScore[]}) {
  if(dimensions.length<3)return <p className={s.hint}>暂无足够的维度数据</p>;
  const point=(index:number,r:number)=>{const a=index*2*Math.PI/dimensions.length-Math.PI/2;return [150+Math.cos(a)*r,130+Math.sin(a)*r];};
  return <svg className={s.abilityRadar} viewBox="0 0 300 265" role="img" aria-label="面试能力雷达图">{[1,.75,.5,.25].map(scale=><polygon key={scale} points={dimensions.map((_,i)=>point(i,82*scale).join(',')).join(' ')} fill={scale===1?'#f8fbff':'none'} stroke="#dbe7f6"/>)}{dimensions.map((_,i)=><line key={i} x1="150" y1="130" x2={point(i,82)[0]} y2={point(i,82)[1]} stroke="#dbe7f6"/>)}<polygon className={s.radarFill} points={dimensions.map((d,i)=>point(i,82*Math.max(0,Math.min(1,d.score/(d.maxScore||100)))).join(',')).join(' ')} fill="#57a8fb55" stroke="#318cf7" strokeWidth="1.5"/>{dimensions.map((d,i)=>{const [x,y]=point(i,109);const [px,py]=point(i,82*Math.max(0,Math.min(1,d.score/(d.maxScore||100))));return <g key={d.dimension}><circle cx={px} cy={py} r="3" fill="#2786f8"/><text x={x} y={y-4} textAnchor="middle" fontSize="11" fill="#53617a">{d.dimension}</text><text x={x} y={y+12} textAnchor="middle" fontSize="12" fill="#1879ec">{d.score}</text></g>;})}</svg>;
}
